version: "2.1"

services:
  cli:
    environment:
      # Make mysql environment variables from docksal.env available to the cli container.
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_USER
      - DOCKSAL_ENVIRONMENT

  db:
    volumes:
      # Mount the db folder from the project root into the database container to allow it to
      #  auto-import any .sql files in there.
      - ${PROJECT_ROOT}/db:/docker-entrypoint-initdb.d:ro

  # Add mailhog to the docksal services to start.
  mail:
    hostname: mail
    image: mailhog/mailhog
    expose:
      - "80"
    environment:
      - MH_API_BIND_ADDR=0.0.0.0:80
      - MH_UI_BIND_ADDR=0.0.0.0:80
    labels:
      - io.docksal.virtual-host=webmail.${VIRTUAL_HOST}
    user: root

  # Adminer
  adminer:
    hostname: adminer
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=db # db is the default database container
      - ADMINER_PLUGINS=tables-filter tinymce # To load Adminer plugins
      - ADMINER_DESIGN=price # To use a bundled Adminer design
    labels:
      - io.docksal.virtual-host=adminer.${VIRTUAL_HOST}